### ISSUE TITLE
centerSelectTextColor 设置了无效，而且默认颜色和selectTextColor也不一致

### ISSUE THREAD

**Issue by Boliang-Lu** [Vincent7Wong/EasyNavigation#60]
![image](https://user-images.githubusercontent.com/32253349/89512697-29bee080-d806-11ea-8920-af1e5eeaa510.png)
这样设置了，点击Add中间按钮，textView后不会改变颜色

**Comment by Amyitis** [comment]
我也发现这个问题
![image](https://user-images.githubusercontent.com/17948294/97070870-48b35e80-160e-11eb-9c4a-946bda5d12b2.png)
中间图标下的文字颜色设置无效。

**Comment by hardlove** [comment]
我也发现这个问题，怎么修改呢

**Comment by Boliang-Lu** [comment]
> 我也发现这个问题，怎么修改呢

下载源码该代码，然后按模块的方式引入
